---
- name: Create device 
  block:
  - name: Create device group 
    uri:
      headers: "{{ tmp_auth_header_fact }}"
      url: https://console.redhat.com/api/edge/v1/device-groups/
      body_format: json
      method: POST
      body: "{{ lookup('template', 'device-group.yaml.j2') }}"
      status_code: 201
