---
- name: Configure offline token 
  import_tasks: ai-svc/setup_auth_headers.yaml
  tags: always 

- name: Create Device Group 
  import_tasks: create-device-group.yml
  tags: 
  - create_device_group

- name: Build Image 
  import_tasks: build-image.yml
  tags: 
  - build_image

- name: Get Build Status 
  import_tasks: get-build-status.yml
  tags: 
  - get_build_status
  
- name: Download the latest iso build
  import_tasks: download-iso.yml
  tags: 
  - download_latest_iso